### ISSUE TITLE
BTC 202 - Setting up your first Bitcoin node

### ISSUE THREAD

**Issue by Rogzy-DB** [DecouvreBitcoin/sovereign-university-data#1344]
### Part 1 - Why being a sovereign bitcoiner

1. what is a bitcoin node 
2. why running a bitcoin node? 
3. different types of bitcoin node
4. what are the software solution for running a node? 
5. what are the hardware solution ?

### Part 2 - How to setup a plug-and-play node 

1. Intro to Umbrel product (DIY solution ThinkCenter with SSD and 8Go or [this](https://x.com/KeithMukai/status/1684243123155742738))
2. Full Bitcoin Node Tutorial installation (bitcoin core and electrum)
3. Overview of Umbrel (+ mempool installation)
4. Mempool overview 
5. Connect your wallet to your node

### Part 3 - Connect your wallet to your node

1. what is electrum / fulcrum (indexer)
2. what open port ? network config? why tor being use
3. connect your wallet tuto 

### Part 4 - go Deeper

1. IBD 
2. `.conf` (policy rules)
3. why build your LN node

**Comment by Rogzy-DB** [comment]
I propose to rename this courses BTC 202 so we can have "BTC 201  - Bitcoin in our society" https://github.com/orgs/PlanB-Network/projects/5/views/1?pane=issue&itemId=92074181

**Comment by LoicPandul** [comment]
I’ll start working on it as soon as I finish NET 302 and the tutorials

**Comment by LoicPandul** [comment]
Next steps:
- [x] Order the hardware (Loïc)
- [x] Write the course in FR (Loïc)
- [x] Write the quiz in FR (Loïc)
- [x] Merge testnet_only (Loïc)
- [x] Review (Asi0 and Rogzy?)
- [x] English translation (Mari)
- [x] English review (Mari)
- [x] Translation into other languages (Mari)
- [x] Add to mainnet (Mari/Asi0/Loïc)

**Comment by LoicPandul** [comment]
New structure for fr.md : 

```md
Partie 0 - Devenez un bitcoiner souverain (73675ebe-fea5-4ce8-83d6-229f09cb316a)

Partie 1 - Introduction (fc46ccd7-5d6d-40c3-9e9f-fbbb323c760a)
    Chapitre 1 - Aperçu du cours (916b1f86-38a4-4ede-bdb7-83841d5a7abe)
    Chapitre 2 - Qu’est-ce qu’un nœud Bitcoin ? (0a9fd4e0-94ab-405e-924c-023397393027)
    Chapitre 3 - Quelle est la différence entre un nœud et un portefeuille ? (de5af634-a628-4b90-b869-468c208e178b)
    Chapitre 4 - Quelle est la différence entre un nœud et un mineur ? (d2992614-7ab7-4bf9-81b1-f548cda67257)
    Chapitre 5 - Bitcoin Core et les implémentations du protocole (72381876-9317-4faa-8d41-2b252a945b8a)

Partie 2 - Devenir un bitcoiner souverain (df64cad2-e92d-4949-9cca-14394aad0bc6)
    Chapitre 1 - Pourquoi faire tourner son propre nœud ? (39c0cd19-67f9-4c64-bfb3-dbd6eec0bf42)
    Chapitre 2 - Les différents types de nœuds Bitcoin (be8f0baa-41f2-4b54-b011-092f4ccc93aa)
    Chapitre 3 - Panorama des solutions logicielles (0d48b89a-e8b5-441e-a707-537a035fc15e)
    Chapitre 4 - Panorama des solutions matérielles (245d6add-9cda-46b9-9343-31dcdd70456e)

Partie 3 - Installer un nœud Bitcoin facilement (ca6cf2a5-0bcc-41d9-b556-0d38865bf98f)
    Chapitre 1 - Umbrel : bien plus qu'un nœud Bitcoin (dd4c04f1-924a-43e1-94f3-ea9fbc83dd43)
    Chapitre 2 - Installation d’un nœud complet avec Umbrel (61bc09c7-787d-4649-b142-457ec018b0f4)

Partie 4 - Connecter son portefeuille à son nœud (418d0afd-3a61-4b5a-9db4-203c0335fd29)
    Chapitre 1 - Les indexeurs : rôle, fonctionnement et solutions (4f93c07a-f0cb-435f-8b68-162f316d7039)
    Chapitre 2 - Comment connecter son portefeuille à son nœud Bitcoin ? (35519b1a-f681-4a69-a652-9fbe510cd17f)
    Chapitre 3 - Tour d’horizon des applications disponibles (2a5ccfbe-0b17-44c9-863c-b7e8cb4b4594)

Partie 5 - Concepts avancés et bonnes pratiques (fc77a62a-8d9f-4144-9080-3057b04db2c6)
    Chapitre 1 - Entretenir son nœud Umbrel (06d77d09-bf24-4555-b2ba-c08bbda477c7)
    Chapitre 2 - Comprendre l’IBD et le processus de découverte des pairs (175ac9d1-ea23-45d9-9918-d3e7352435cd)
    Chapitre 3 - Anatomie de votre nœud Bitcoin (b420bd9d-7e2a-4984-bc70-2b732a94c8ce)
    Chapitre 4 - Comprendre le fichier bitcoin.conf (c54a629a-ddb1-41cb-9a88-21dfd9be50ca)

Partie 6 - Partie finale (679169f5-b990-47e1-9a00-45098ba8096b)
    Chapitre 1 - Avis & Notes (c18f672d-1074-427e-9505-eecd7ae43e71)
    Chapitre 2 - Examen final (a4c97701-996c-4cc5-81fa-37d2dc4ee856)
    Chapitre 3 - Conclusion (28c5cf1f-7b9c-4b68-8b8f-eee109629764)
```
